### ISSUE TITLE
[PE-D][Tester E] Corrupted save.txt leads to crashing of app

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T13-3/tp#114]
![image.png](https://raw.githubusercontent.com/firwer/ped/main/files/fabeeb11-b096-40d2-b753-c792b1021028.png)
### Steps to reproduce:
1. In a fresh/empty save.txt, add this line: `testuser;1212;0; ; ;1.0;9999-12-31`
2. Start the app
3. Do a `withdraw 1`

### Expected:
To be able to withdraw $1 OR the corrupted file to be detected and restricted from use on startup

### Actual:
I am able to open the app as usual and conduct operation which crashed the app

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: firwer/ped#1

**Comment by vishnuvk47** [comment]
<img width="1100" alt="Screenshot 2023-04-01 at 1 11 54 PM" src="https://user-images.githubusercontent.com/122626659/229266899-5e672c5d-763b-45c0-a096-98ec0b178e18.png">

In response to the bug report, I would like to point out that this issue was clearly stated in the User Guide. Additionally, we provided instructions for the user to address the problem by deleting the save files and restarting the system. It is important to note, however, that this action of corrupting the save files will lead to irreversible loss of data.

**Comment by vishnuvk47** [comment]
since PR #143 has been merged I will close this issue, as that PR aims to solve this issue
