### ISSUE TITLE
[PE-D][Tester A] [Bug] Printing bug is found in the start of the program when there are multiple existing accounts.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T13-3/tp#115]
If I restart the program after creating multiple accounts, there is message appeared like `There is no saved account, please create a new account`. Refer the image below:

<img src="https://raw.githubusercontent.com/0nandon/ped/main/files/41bb9d85-b0fe-4839-9d26-4460ab82bbcc.png" width=400>

And also, if I try appropriate command like `delete` after that, program automatically creates new account with the name of the `delete`. Refer the image below:

<img src="https://raw.githubusercontent.com/0nandon/ped/main/files/6754e9d5-1ed5-4690-96c7-8b4a0947cbfb.png" width=400>

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: 0nandon/ped#3

**Comment by vishnuvk47** [comment]
will need to resole this as per issue #63. However, the problem is not related to the creation of a new account with an empty name. Instead, the current delete method is problematic because it uses the .contains() function, which can result in the current account being mistakenly identified as the account to be deleted if it has an empty name (i.e., matches the .contains(" ") condition). As a consequence, the program deletes the current account, leading to the message "account: deleted" being displayed as the ui.showAccount deleted used the argument to the delete command as a param which was " ". I think I have resolved this bug in the latest PR #109 .
